Repository David-Lor/pnytter, pull requests merged in 2022-10, with the labels that each got.

#6 avoid crash when no bio is available
  pnytter/nitter_parser/profiles.py
  tests/test_pnytter_profiles.py
Labels: type/bug, hacktoberfest-accepted

#10 test: fix assertions
  .github/workflows/test.yaml
  pnytter/pnytter.py
  pytest.ini
  requirements-test.txt
  tests/_test_pnytter_tweets_data.py
  tests/test_pnytter_profiles.py
  tests/test_pnytter_tweets.py
Labels: type/internal, hacktoberfest-accepted

#12 fix: avoid crash when no profile pictures are available
  pnytter/models/profiles.py
  pnytter/nitter_parser/profiles.py
  tests/test_pnytter_profiles.py
Labels: type/bug, hacktoberfest-accepted

#11 Release v0.2.1
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  README.md
  pnytter/models/profiles.py
  pnytter/nitter_parser/profiles.py
  pnytter/pnytter.py
  pytest.ini
  requirements-test.txt
  tests/_test_pnytter_tweets_data.py
  tests/test_pnytter_profiles.py
  tests/test_pnytter_tweets.py
Labels: release, hacktoberfest-accepted
